name: Run API Tests

on:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run collection.json -r cli,html
          ls   

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/